apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laptop-advise.fullname" . }}-config
data:
{{- range $key, $value := .Values.laravel.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
  DB_HOST: {{ include "laptop-advise.postgresName" . | quote }}
  DB_DATABASE: {{ .Values.postgres.database | quote }}
  DB_USERNAME: {{ .Values.postgres.username | quote }}
